In [4]:
import pandas as pd

## Arbeitnehmerentgelt auf Kreisebene

In [5]:
df = pd.read_excel("vgr_r2b2_bs2020_2.xlsx", sheet_name = "1.1", skiprows = 4)

In [7]:
df.head()

,Lfd. Nr.,EU-Code,Regional-schlüssel,Land,NUTS 1,NUTS 2,NUTS 3,Gebietseinheit,2000,2001,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,DE1,8.0,BW,1.0,NaN,NaN,Baden-Württemberg,165813.881,170837.899,...,196903.258,206590.170,216018.525,223563.429,231809.508,240974.383,250357.652,261783.348,272500.477,282790.938
2,2.0,DE11,81.0,BW,NaN,2.0,NaN,"Stuttgart, Regierungsbezirk",68958.335,71188.331,...,81556.034,86167.696,90392.092,93988.130,97455.325,101896.826,106012.099,111294.210,116066.502,119724.141
3,3.0,DE111,8111.0,BW,NaN,NaN,3.0,"Stuttgart, Landeshauptstadt, Stadtkreis",18416.060,19070.243,...,21648.134,22751.949,24053.093,24876.178,26166.884,27500.233,28177.149,29686.210,31104.601,31477.938
4,4.0,DE112,8115.0,BW,NaN,NaN,3.0,"Böblingen, Landkreis",7455.367,7892.426,...,9185.528,9750.509,10135.229,10615.200,10674.022,11254.471,11954.421,12597.680,12903.227,13289.979

In [8]:
df.rename(columns = {"Regional-schlüssel": "kreis_key", 2019 : "income"}, inplace = True)
df = df[["kreis_key", "income"]].dropna()
df.kreis_key = df.kreis_key.astype(int)
df.kreis_key.replace({2 : 2000, 11 : 11000}, inplace = True) # Fix Regional codes of Hamburg (2) and Berlin (11)

In [48]:
df.to_csv("income.csv")